name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events.
on: [ push, pull_request ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container: wpilib/roborio-cross-ubuntu:2023-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Check and print all dependencies
      run: ./gradlew dependencies

    - name: Check and print all Java toolchains
      run: ./gradlew javaToolchains

    - name: Build and test robot code
      run: ./gradlew build